const { db, queries } = require('./db');

const seedQuestions = [
  "Does intelligent life exist on other planets?",
  "Will you visit space in your lifetime?",
  "Is it wrong to take steroids for muscles?",
  "Will there be a World War III?",
  "Was Covid created in a Chinese lab?",
  "Will humanity survive another 1,000 years?",
  "Do human souls or consciousness live on after death?",
  "Is it wrong to use heroin?",
  "Would you put a chip in your brain for faster/increased knowledge? (Neuralink)",
  "Will humans ever be able to live to 200+ years old through scientific advancement?",
  "Would you get elective cosmetic plastic surgery?",
  "Would you euthanize a friend if they begged you to?",
  "Would you euthanize a stranger if they begged you to?",
  "Is death by suicide ever reasonable or permissible?",
  "Is the death penalty ethically wrong?",
  "Will we live to see major climate disasters? (Day After Tomorrow scale)",
  "Will world hunger ever be solved?",
  "Is it possible to end homelessness in America?",
  "Does God/the universe use psychedelic drugs to reveal themself to people?",
  "Are professional sports good for humanity?",
  "Is it possible to live to 80 and never lie?",
  "Is war ever justifiable?",
  "Will anyone in this room become famous?",
  "Will anyone in this room ever join an MLM?",
  "Are all people born good?",
  "Do we have free will?",
  "Should we, as a society, take measures to ensure that severely mentally handicapped children aren't born? (Re: Iceland)",
  "If you had a terminal illness and money wasn't a barrier, would you cryogenically freeze yourself before you died naturally?",
  "If you could switch your life with a person of your choosing, would you?",
  "Will we have a female President in our lifetime?",
  "Will the institution of college exist in 50 years?",
  "Are a cheese pizza and a cheese stick dipped in marinara the same thing?",
  "Do you brush your teeth before eating breakfast?",
  "Do you wash your legs when you shower?",
  "Bidet?",
  "Do you fold your toilet paper when wiping?",
  "Is male circumcision wrong?",
  "Is art purely subjective?",
  "Is having a child selfish?",
  "Do you think voting matters?",
  "If you could kill any one person without consequences, by simply wishing it, would you?",
  "Should trans athletes be allowed to compete in their gender-affirming category?",
  "Are pit bulls inherently more dangerous than other breeds of dogs?",
  "Is it wrong to not keep up with the news?",
  "Is porn bad for society?",
  "Should women's sports athletes be paid as much as men's sports athletes?",
  "Are all human lives of equal value?",
  "Did your parents do a good job?",
  "Does lobster taste good?",
  "Should student loans be forgiven?",
  "Will self-driving cars be good for society?",
  "Is the concept of a zoo ethical?",
  "Will the United States still be a country in 100 years?",
  "Would you let your kid play football if they asked to?",
  "Are all cops bad?",
  "Are dating apps good for society?",
  "Christmas music before Thanksgiving?",
  "Will the world be a better place in 100 years?",
  "Would you eat a human if you were starving to death?",
  "Is spanking a good way to discipline a child?",
  "Would you press a button that doubled your IQ?",
  "Can plants feel pain?",
  "Is torture ever permissible?",
  "Would you be willing to show your browsing history to everybody present?",
  "What if this didn't include porn?",
  "Can someone both be a good person and also hold the exact opposite of your political views?",
  "At the gut level, do you feel that the world is safe?",
  "Are you afraid of death?",
  "Do you believe in reincarnation?",
  "If you could press a button that would make you feel deeply and permanently that everything was ok, would you?",
  "Do you have any political or social opinions that you're afraid to express out loud to your friends?",
  "Are there any thoughts so offensive that you would advocate shaming those who think them, even if they don't act on those thoughts?",
  "Do you inherently owe your parents anything?",
  "Do you recline on an airplane?",
  "Is pain relative?",
  "Are all romantic relationships delusions?",
  "Is catch-and-release fishing unethical?",
  "Is it unethical to watch people through their windows? (Re: Rear Window)",
  "Is this a simulation?",
  "Is it okay to just work all the time?",
  "Are cults always bad?",
  "If you could snap your fingers and make every weapon on earth disappear, would you do it?",
  "Is America the greatest country on Earth?",
  "Was America ever the greatest country on Earth?",
  "Without taking into account your loved ones and life experiences, do you wish you were born in a different country?",
  "Is it gross to let a dog lick you on the mouth?",
  "Should people risk their lives trying to save someone who was lost/stranded/injured doing a recreational activity?",
  "If you had the ability to know when your life would end, would you want to?",
  "What about how you die, but not when?",
  "Subtitles?",
  "Do you know how to bleach clothes in a washing machine?",
  "Are you good at saving money?",
  "Is it unethical to buy a purebred dog from a breeder?",
  "Is it unethical to ride in a Waymo?",
  "If someone doesn't like dogs, are they a bad person?",
];

const insertMany = db.transaction((questions) => {
  for (const text of questions) {
    queries.addQuestion.run(text, null, 'seed');
  }
});

insertMany(seedQuestions);

const count = queries.getQuestionCount.get().count;
console.log(`Database seeded. Total questions: ${count}`);
